---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: frontend-monitoring-pa11y
env:
  gar_docker_registry : ${{ vars.GAR_DOCKER_REGISTRY }}
spec:
  concurrencyPolicy: Forbid
  schedule: "20 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pa11y
            image: ${{ vars.GAR_DOCKER_REGISTRY }}/frontend-monitoring:v0.1
            command:
            - npm
            - run
            - pa11y
            - --no-update-notifier
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: frontend-monitoring-cssstats
spec:
  concurrencyPolicy: Forbid
  schedule: "50 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cssstats
            image: ${{ vars.GAR_DOCKER_REGISTRY }}/frontend-monitoring:v0.1
            command:
            - npm
            - run
            - cssstats
            - --no-update-notifier
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: frontend-monitoring-htmlvalidator
spec:
  concurrencyPolicy: Forbid
  schedule: "40 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: htmlvalidator
            image: ${{ vars.GAR_DOCKER_REGISTRY }}/frontend-monitoring:v0.1
            command:
            - npm
            - run
            - htmlvalidator
            - --no-update-notifier
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: frontend-monitoring-homepagestats
spec:
  concurrencyPolicy: Forbid
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: homepagestats
            image: ${{ vars.GAR_DOCKER_REGISTRY }}/frontend-monitoring:v0.1
            command:
            - npm
            - run
            - homepagestats
            - --no-update-notifier
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: frontend-monitoring-adplaces
spec:
  concurrencyPolicy: Forbid
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: adplaces
            image: ${{ vars.GAR_DOCKER_REGISTRY }}/frontend-monitoring:v0.1
            command:
            - npm
            - run
            - adplaces
            - --no-update-notifier
          restartPolicy: OnFailure
