apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cron-job.yaml
images:
- name: europe-west3-docker.pkg.dev/zeitonline-engineering/docker-zon/frontend-monitoring
  newTag: efaa86afdcc10ad8772c644c7deef0829501b048
