name: Build

on:
  push:
    branches:
      - main

env:
  ENVIRONMENT: production
  PROJECT: frontend-monitoring

jobs:
  build:
    name: Build Frontend Monitoring
    runs-on: zon-ubuntu-general-dind

    permissions:
      id-token: write
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Baseproject
        id: baseproject
        uses: ZeitOnline/gh-action-baseproject@v0
        with:
          project_name: ${{ env.PROJECT }}
          environment: ${{ env.ENVIRONMENT }}
          gke_auth: true
          gar_docker_auth: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          driver: docker

      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.GAR_DOCKER_REGISTRY }}/${{ env.PROJECT }}:${{ github.sha }}
            ${{ vars.GAR_DOCKER_REGISTRY }}/${{ env.PROJECT }}:latest

      - name: kustomize image tag
        run: |
          cd k8s
          kustomize edit set image ${{ secrets.GAR_DOCKER_REGISTRY }}/${{ steps.baseproject.outputs.project_name }}:${{ github.sha }}

      - name: auto commit
        id: auto_commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GHA: bump image version to ${{ github.sha }} for deployments"
          file_pattern: k8s/
