name: Deployment

on:
  push:
    branches:
      - main

env:
  ENVIRONMENT: production
  PROJECT: frontend-monitoring

jobs:
  build-and-deploy:
    name: Deploy Frontend Monitoring
    runs-on: [self-hosted, linux]

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Baseproject
        id: baseproject
        uses: ZeitOnline/gh-action-baseproject@v0
        with:
          project_name: ${{ env.PROJECT }}
          environment: ${{ env.ENVIRONMENT }}
          gke_auth: true
          gcr_auth: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          driver: docker

      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.GCR_IMAGE_REGISTRY }}/${{ steps.baseproject.outputs.project_name }}:${{ github.sha }}
            ${{ secrets.GCR_IMAGE_REGISTRY }}/${{ steps.baseproject.outputs.project_name }}:latest

      - name: Deploy to K8s
        uses: ZeitOnline/gh-action-gke-deployer@v0
        with:
          command: |
            cd k8s
            kustomize edit set image ${{ secrets.GCR_IMAGE_REGISTRY }}/${{ steps.baseproject.outputs.project_name }}:${{ github.sha }}
            kustomize build . | kubectl -n ${{ steps.baseproject.outputs.project_name }} apply -f -
